/** Generated by Gradle from android/app/google-services.json — do not edit. */
export const GOOGLE_WEB_CLIENT_ID_FROM_FIREBASE: string | null = '408638792904-bjj0a2ap9ic3ln2aghp0c5vhuf8d2hph.apps.googleusercontent.com';
export const GOOGLE_ANDROID_PACKAGE_FROM_FIREBASE = 'com.speakupmic';
